# Generated by Django 3.2 on 2021-05-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210505_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedetail',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
