# Generated by Django 3.2 on 2021-05-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210505_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likedetail',
            options={'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
    ]
