# Generated by Django 3.2 on 2021-05-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_likedetail_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedetail',
            name='created',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
